import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "on-tertiary": "#3e2e00",
        background: "#141218",
        "primary-container": "#6750a4",
        "on-surface-variant": "#cbc4d2",
        "surface-container": "#211f24",
        "on-primary": "#381e72",
        "surface-container-lowest": "#0f0d13",
        "secondary-fixed": "#e9ddff",
        outline: "#948e9c",
        tertiary: "#e7c365",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#cdc0e9",
        "on-surface": "#e6e0e9",
        "on-background": "#e6e0e9",
        "inverse-surface": "#e6e0e9",
        "on-primary-fixed-variant": "#4f378a",
        "on-error": "#690005",
        "on-secondary-fixed": "#1f1635",
        "primary-fixed": "#e9ddff",
        "tertiary-fixed": "#ffdf93",
        "inverse-on-surface": "#322f35",
        "on-tertiary-fixed": "#241a00",
        "primary-fixed-dim": "#cfbcff",
        "on-secondary-fixed-variant": "#4b4263",
        "surface-container-high": "#2b292f",
        "on-tertiary-container": "#503d00",
        "surface-tint": "#cfbcff",
        "outline-variant": "#494551",
        "surface-container-low": "#1d1b20",
        "surface-bright": "#3b383e",
        "surface-variant": "#36343a",
        "on-primary-fixed": "#22005d",
        "on-primary-container": "#e0d2ff",
        primary: "#cfbcff",
        "surface-container-highest": "#36343a",
        "surface-dim": "#141218",
        "tertiary-fixed-dim": "#e7c365",
        "on-secondary-container": "#bfb2da",
        "inverse-primary": "#6750a4",
        "on-error-container": "#ffdad6",
        surface: "#141218",
        "secondary-container": "#4d4465",
        secondary: "#cdc0e9",
        "on-tertiary-fixed-variant": "#594400",
        "on-secondary": "#342b4b",
        "tertiary-container": "#c9a74d",
        "brand-orange": "#f95d24",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        grid_unit: "8px",
        gutter: "24px",
        margin_desktop: "64px",
        margin_mobile: "20px",
        section_gap: "120px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-geist)", "sans-serif"],
        "headline-xl": ["var(--font-geist)", "sans-serif"],
        "body-md": ["var(--font-geist)", "sans-serif"],
        "headline-lg": ["var(--font-geist)", "sans-serif"],
        "stat-value": ["var(--font-geist)", "sans-serif"],
        "label-technical": ["var(--font-jetbrains)", "monospace"],
        "display-lg": ["var(--font-geist)", "sans-serif"],
        geist: ["var(--font-geist)", "sans-serif"],
        mono: ["var(--font-jetbrains)", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "115%", fontWeight: "700" },
        ],
        "headline-xl": [
          "56px",
          { lineHeight: "100%", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "150%", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "110%", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "stat-value": ["48px", { lineHeight: "100%", fontWeight: "600" }],
        "label-technical": [
          "12px",
          { lineHeight: "100%", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "display-lg": [
          "84px",
          { lineHeight: "90%", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
